# Generated by Django 5.2.17 on 2026-09-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='draft_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
