# Generated by Django 5.2.17 on 2026-09-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_assignmentquestion_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='source_document_file_id',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
