# Generated by Django 5.2.17 on 2026-09-25 11:30

import django.db.models.deletion
from django.db import migrations, models


def map_legacy_module_codes(apps, schema_editor):
    AssignmentModel = apps.get_model("assignments", "AssignmentModel")
    code_map = {"model_1": "practice", "model_2": "mock", "model_3": "mock"}
    name_map = {"Direct MCQ": "Practice", "Tests": "Mock Test", "Tests & Sets": "Mock Test"}
    for old_code, new_code in code_map.items():
        AssignmentModel.objects.filter(code=old_code).update(code=new_code)
    for old_name, new_name in name_map.items():
        AssignmentModel.objects.filter(name=old_name).update(name=new_name)
    # Anything else predates the module system; park it on mock.
    AssignmentModel.objects.exclude(code__in=["practice", "mock"]).update(code="mock")


def unmap_legacy_module_codes(apps, schema_editor):
    AssignmentModel = apps.get_model("assignments", "AssignmentModel")
    reverse = {"practice": "model_1", "mock": "model_2"}
    for new_code, old_code in reverse.items():
        AssignmentModel.objects.filter(code=new_code).update(code=old_code)


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_assignment_source_document_file_id'),
        ('packs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_instances', to='packs.questionpack'),
        ),
        migrations.RunPython(map_legacy_module_codes, unmap_legacy_module_codes),
        migrations.AlterField(
            model_name='assignmentmodel',
            name='code',
            field=models.CharField(choices=[('practice', 'Practice'), ('mock', 'Mock Test')], max_length=30),
        ),
    ]
