# Generated by Django 5.2.17 on 2026-09-04 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_review'),
        ('enrollments', '0004_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('enrolled', 'Enrolled'), ('viewed_lesson', 'Viewed lesson'), ('completed_lesson', 'Completed lesson'), ('quiz_attempt', 'Quiz attempt'), ('assignment_submitted', 'Submitted assignment'), ('assignment_graded', 'Assignment graded'), ('rated_course', 'Rated course'), ('earned_certificate', 'Earned certificate'), ('session_start', 'Session start')], db_index=True, max_length=24)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='courses.course')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='courses.lesson')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['learner', 'created_at'], name='enrollments_learner_791de1_idx'), models.Index(fields=['course', 'verb', 'created_at'], name='enrollments_course__3998d4_idx')],
            },
        ),
    ]
