# Generated by Django 5.2.17 on 2026-09-25 11:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0005_assignment_source_document_file_id'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('cover', models.URLField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('allowed_modules', models.JSONField(blank=True, default=list)),
                ('max_attempts', models.PositiveIntegerField(default=0)),
                ('test_size', models.PositiveIntegerField(default=25)),
                ('test_duration_seconds', models.PositiveIntegerField(default=1800)),
                ('set_size', models.PositiveIntegerField(default=10)),
                ('set_duration_seconds', models.PositiveIntegerField(default=600)),
                ('execution_mode', models.CharField(default='sequential', max_length=12)),
                ('passing_percentage', models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('negative_marking', models.BooleanField(default=True)),
                ('question_count', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inter_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packs', to='assignments.intercategory')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_packs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_image', models.CharField(blank=True, default='', max_length=500)),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.PositiveIntegerField(default=0)),
                ('explanation', models.TextField(blank=True, default='')),
                ('marks', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('difficulty', models.CharField(default='medium', max_length=10)),
                ('topic', models.CharField(blank=True, default='', max_length=120)),
                ('position', models.PositiveIntegerField(default=0)),
                ('source', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='packs.questionpack')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PackPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('attempts_used', models.PositiveIntegerField(default=0)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_purchases', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pack_purchases', to='payments.payment')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='packs.questionpack')),
            ],
            options={
                'ordering': ['-purchased_at'],
                'unique_together': {('learner', 'pack')},
            },
        ),
    ]
