# Generated by Django 5.2.17 on 2026-08-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_average_rating_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='kind',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('quiz', 'Quiz'), ('link', 'External link'), ('audio', 'Audio')], default='video', max_length=10),
        ),
        migrations.AddField(
            model_name='lesson',
            name='resource_url',
            field=models.URLField(blank=True),
        ),
    ]
