# Generated by Django 5.2.17 on 2026-08-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_kind_lesson_resource_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='kind',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('quiz', 'Quiz'), ('link', 'External link'), ('audio', 'Audio'), ('text', 'Text / Markdown')], default='video', max_length=10),
        ),
    ]
