# Generated by Django 5.2.17 on 2026-08-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_lesson_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='quiz_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
