# Generated by Django 5.2.17 on 2026-08-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_quiz_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='what_you_will_learn',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
