# Generated by Django 5.2.17 on 2026-09-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_what_you_will_learn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='resource_url',
            field=models.TextField(blank=True),
        ),
    ]
