# Generated by Django 5.2.17 on 2026-09-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_lesson_resource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='course',
            name='pg_fees_to_learner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='pricing_type',
            field=models.CharField(choices=[('free', 'Free'), ('one_time', 'One-time')], default='free', max_length=10),
        ),
    ]
