# Generated by Django 5.2.17 on 2026-09-30 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_pack_alter_payment_course_and_more'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='promotions.coupon'),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_paise',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
